package com.qsoft.tictactoe.ui.view;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import com.qsoft.tictactoe.ui.controller.ButtonController;
import com.qsoft.tictactoe.ui.controller.MainPanelController;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionListener;
import java.util.ArrayList;

/**
 * User: luult
 * Date: 8/16/13
 * Time: 8:26 AM
 */
@Component
public class MainWindow extends JFrame
{
    public static final String APPLICATION_TITLE = "Tit tac toe game";
    public static final String MAIN_WINDOW_NAME = "Tic tac toe game";
    public static final String START_BUTTON_NAME = "btStart";
    public static final String STOP_BUTTON_NAME = "btStop";
    public static final String LABEL_STATUS_NAME = "lbStatus";
    private JPanel panel1;
    private JPanel buttonPanel;
    private JButton btStart;
    private JButton btStop;
    private JPanel labelPanel;
    private JLabel lbStatus;
    private JPanel mainPanel;
    @Autowired
    private ButtonController buttonController;

    @Autowired
    private MainPanelController mainPanelController;

    private ArrayList<JButton> buttonList = new ArrayList<JButton>();

    public JButton getBtStart()
    {
        return btStart;
    }

    public JButton getBtStop()
    {
        return btStop;
    }

    public JLabel getLbStatus()
    {
        return lbStatus;
    }

    public JPanel getMainPanel()
    {
        return mainPanel;
    }

    public void setContentPanel()
    {

        setName(MAIN_WINDOW_NAME);
        setTitle(APPLICATION_TITLE);
        setMinimumSize(new Dimension(500, 500));
        setContentPane(panel1);
        pack();
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setVisible(true);
        addMainPanel();
        mainPanel.setVisible(false);
    }

    private void addMainPanel()
    {
        mainPanel.setLayout(new GridLayout(3, 3));
        for (int i = 0; i < 9; i++)
        {
            String name = "button" + i;
            JButton jButton = new JButton("");
            jButton.setActionCommand(i + "");
            jButton.setName(name);
            jButton.addActionListener(mainPanelController);
            mainPanel.add(jButton);
            buttonList.add(jButton);
        }
    }

    public void addListener()
    {
        btStart.addActionListener(buttonController);
        btStop.addActionListener(buttonController);
    }

    public JButton getButton(String name)
    {
        return buttonList.get(Integer.parseInt(name));  //To change body of created methods use File | Settings | File Templates.
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$()
    {
        panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new BorderLayout(0, 0));
        panel2.setName("btStatus");
        panel1.add(panel2, BorderLayout.NORTH);
        buttonPanel = new JPanel();
        buttonPanel.setLayout(new GridLayoutManager(1, 3, new Insets(0, 0, 0, 0), -1, -1));
        buttonPanel.setMaximumSize(new Dimension(172, 29));
        panel2.add(buttonPanel, BorderLayout.CENTER);
        btStart = new JButton();
        btStart.setName("btStart");
        btStart.setText("Start");
        buttonPanel.add(btStart, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btStop = new JButton();
        btStop.setEnabled(false);
        btStop.setName("btStop");
        btStop.setText("Stop");
        buttonPanel.add(btStop, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        buttonPanel.add(spacer1, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        labelPanel = new JPanel();
        labelPanel.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        labelPanel.setMinimumSize(new Dimension(40, 20));
        panel2.add(labelPanel, BorderLayout.NORTH);
        lbStatus = new JLabel();
        lbStatus.setName("lbStatus");
        lbStatus.setText("");
        labelPanel.add(lbStatus, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, new Dimension(40, 20), null, null, 0, false));
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        panel1.add(mainPanel, BorderLayout.CENTER);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$()
    {
        return panel1;
    }
}
