package com.qsoft.ui;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import com.qsoft.controller.MainWindowController;

import javax.imageio.ImageIO;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;

/**
 * User: luult
 * Date: 8/8/13
 * Time: 8:49 AM
 */
public class MainWindow extends JFrame
{
    public static final String MAIN_WINDOW_NAME = "Tic tac toe game";
    public static final String APPLICATION_TITLE = "Tic tac toe game";
    public static final String START_BUTTON_NAME = "btStart";
    public static final String END_BUTTON_NAME = "btEnd";
    public static final String LABEL_STATUS_NAME = "lbStatus";
    private JPanel panel1;
    private JButton btStart;
    private JButton btEnd;
    private JLabel lbStatus;
    private JButton button1;
    private JButton button2;
    private JButton button3;
    private JButton button6;
    private JButton button5;
    private JButton button4;
    private JButton button9;
    private JButton button8;
    private JButton button7;
    MainWindowController mainWindowController;

    public MainWindow()
    {
        setName(MAIN_WINDOW_NAME);
        setTitle(APPLICATION_TITLE);
        setMinimumSize(new Dimension(500, 500));
        setContentPane(panel1);

        pack();

//        JButton button = new JButton();
//        try {
//            Image img = ImageIO.read(getClass().getResource("/cross.png"));
//            button.setIcon(new ImageIcon(img));
//        } catch (IOException ex) {
//        }
//        panel1.add(button);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setVisible(true);
        mainWindowController = new MainWindowController(this);
        btStart.addActionListener(mainWindowController);
        btEnd.addActionListener(mainWindowController);
        button1.addActionListener(mainWindowController);
        button2.addActionListener(mainWindowController);
        button3.addActionListener(mainWindowController);
    }

    public JButton getButton1()
    {
        return button1;
    }

    public void setButton1(JButton button1)
    {
        this.button1 = button1;
    }

    public JButton getButton2()
    {
        return button2;
    }

    public void setButton2(JButton button2)
    {
        this.button2 = button2;
    }

    public JButton getButton3()
    {
        return button3;
    }

    public void setButton3(JButton button3)
    {
        this.button3 = button3;
    }

    public JButton getButton6()
    {
        return button6;
    }

    public void setButton6(JButton button6)
    {
        this.button6 = button6;
    }

    public JButton getButton5()
    {
        return button5;
    }

    public void setButton5(JButton button5)
    {
        this.button5 = button5;
    }

    public JButton getButton4()
    {
        return button4;
    }

    public void setButton4(JButton button4)
    {
        this.button4 = button4;
    }

    public JButton getButton9()
    {
        return button9;
    }

    public void setButton9(JButton button9)
    {
        this.button9 = button9;
    }

    public JButton getButton8()
    {
        return button8;
    }

    public void setButton8(JButton button8)
    {
        this.button8 = button8;
    }

    public JButton getButton7()
    {
        return button7;
    }

    public void setButton7(JButton button7)
    {
        this.button7 = button7;
    }

    public JLabel getLbStatus()
    {
        return lbStatus;
    }

    public void setLbStatus(JLabel lbStatus)
    {
        this.lbStatus = lbStatus;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$()
    {
        panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new BorderLayout(0, 0));
        panel1.add(panel2, BorderLayout.NORTH);
        lbStatus = new JLabel();
        lbStatus.setHorizontalAlignment(0);
        lbStatus.setMinimumSize(new Dimension(40, 20));
        lbStatus.setName("lbStatus");
        lbStatus.setPreferredSize(new Dimension(40, 20));
        lbStatus.setText("");
        panel2.add(lbStatus, BorderLayout.NORTH);
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new GridLayoutManager(2, 3, new Insets(0, 0, 0, 0), -1, -1));
        panel1.add(panel3, BorderLayout.CENTER);
        btStart = new JButton();
        btStart.setName("btStart");
        btStart.setText("Start");
        panel3.add(btStart, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btEnd = new JButton();
        btEnd.setName("btEnd");
        btEnd.setText("Stop");
        panel3.add(btEnd, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        panel3.add(spacer1, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        final JPanel panel4 = new JPanel();
        panel4.setLayout(new GridLayoutManager(3, 3, new Insets(0, 0, 0, 0), -1, -1));
        panel3.add(panel4, new GridConstraints(1, 0, 1, 3, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        button1 = new JButton();
        button1.setActionCommand("button1");
        button1.setFont(new Font(button1.getFont().getName(), button1.getFont().getStyle(), 28));
        button1.setForeground(new Color(-52429));
        button1.setHideActionText(false);
        button1.setHorizontalTextPosition(0);
        button1.setName("button1");
        button1.setOpaque(false);
        button1.setText("");
        panel4.add(button1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        button2 = new JButton();
        button2.setActionCommand("button2");
        button2.setFont(new Font(button2.getFont().getName(), button2.getFont().getStyle(), 48));
        button2.setName("button2");
        button2.setText("");
        panel4.add(button2, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        button3 = new JButton();
        button3.setActionCommand("button3");
        button3.setName("button3");
        button3.setText("");
        panel4.add(button3, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        button6 = new JButton();
        button6.setActionCommand("button6");
        button6.setName("button6");
        button6.setText("");
        panel4.add(button6, new GridConstraints(1, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        button5 = new JButton();
        button5.setActionCommand("button5");
        button5.setName("button5");
        button5.setText("");
        panel4.add(button5, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        button4 = new JButton();
        button4.setActionCommand("button4");
        button4.setName("button4");
        button4.setText("");
        panel4.add(button4, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        button9 = new JButton();
        button9.setActionCommand("button9");
        button9.setName("button9");
        button9.setText("");
        panel4.add(button9, new GridConstraints(2, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        button8 = new JButton();
        button8.setActionCommand("button8");
        button8.setName("button8");
        button8.setText("");
        panel4.add(button8, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        button7 = new JButton();
        button7.setActionCommand("button7");
        button7.setName("button7");
        button7.setText("");
        panel4.add(button7, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$()
    {
        return panel1;
    }
}
