package com.qsoft.ui;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import com.qsoft.controller.MainWindowController;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 * User: luult
 * Date: 8/8/13
 * Time: 8:49 AM
 */
public class MainWindow extends JFrame
{
    public static final String MAIN_WINDOW_NAME = "Tic tac toe game";
    public static final String APPLICATION_TITLE = "Tic tac toe game";
    public static final String START_BUTTON_NAME = "btStart";
    public static final String END_BUTTON_NAME = "btEnd";
    public static final String LABEL_STATUS_NAME = "lbStatus";
    private JPanel panel1;
    private JButton btStart;
    private JButton btEnd;
    private JLabel lbStatus;
    MainWindowController mainWindowController;

    public MainWindow()
    {
        setName(MAIN_WINDOW_NAME);
        setTitle(APPLICATION_TITLE);
        setMinimumSize(new Dimension(500, 500));
        setContentPane(panel1);
        pack();
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setVisible(true);
        mainWindowController = new MainWindowController(this);
        btStart.addActionListener(mainWindowController);
        btEnd.addActionListener(mainWindowController);
    }

    public JLabel getLbStatus()
    {
        return lbStatus;
    }

    public void setLbStatus(JLabel lbStatus)
    {
        this.lbStatus = lbStatus;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$()
    {
        panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new BorderLayout(0, 0));
        panel1.add(panel2, BorderLayout.NORTH);
        lbStatus = new JLabel();
        lbStatus.setHorizontalAlignment(0);
        lbStatus.setMinimumSize(new Dimension(40, 20));
        lbStatus.setName("lbStatus");
        lbStatus.setPreferredSize(new Dimension(40, 20));
        lbStatus.setText("");
        panel2.add(lbStatus, BorderLayout.NORTH);
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new GridLayoutManager(2, 3, new Insets(0, 0, 0, 0), -1, -1));
        panel1.add(panel3, BorderLayout.CENTER);
        btStart = new JButton();
        btStart.setName("btStart");
        btStart.setText("Start");
        panel3.add(btStart, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        panel3.add(spacer1, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        btEnd = new JButton();
        btEnd.setName("btEnd");
        btEnd.setText("Stop");
        panel3.add(btEnd, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer2 = new Spacer();
        panel3.add(spacer2, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$()
    {
        return panel1;
    }
}
